version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build --tag codizz/curl .
      - run:
          command: |
            docker run codizz/curl
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push codizz/curl
           
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
     
