version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Duild docker image
          command: |
            docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                         --build-arg VCS_REF=`git rev-parse --short HEAD` \
                         --build-arg VERSION=`cat $VERSION` \
                         --tag codizz/curl \
                         .

      - run:
          name: Run test
          command: |
            docker run -d codizz/curl

      - run:
          name: Push docker image
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker push codizz/curl
            
