# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Container Scan
on: push
jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Pull the Docker image
      run: docker pull codizz/curl:latest
    - name: Scan image
      uses: anchore/scan-action@v2
      id: scan
      with:
        image: "codizz/curl:latest"
        acs-report-enable: true
        fail-build: true
    - name: Upload Anchore Scan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Inspect Scan Report
      run: cat ${{ steps.scan.outputs.sarif }}

#    - name: Upload Anchore Scan Report
#      uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: results.sarif
